[package]
name = "stuckliste"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.1"
libc = "0.2.164"
normalize-path = "0.2.1"
walkdir = "2.5.0"

[dev-dependencies]
cpio-test = { path = "../cpio/cpio-test" }
