---
name: CI
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igankevich/stuckliste-ci:latest
      options: --cap-add SYS_PTRACE
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
      CIJAIL_ENDPOINTS: |
        https://github.com/lyz-code/yamlfix/
        https://pypi.org/simple/
        https://files.pythonhosted.org/packages/
        https://static.crates.io/crates/
        https://index.crates.io/
        https://github.com/rustsec/advisory-db
        https://static.rust-lang.org/dist/
        https://github.com/igankevich/kpea/
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Init
        run: cijail ./ci/init.sh
      - name: Lint
        run: cijail ./ci/lint.sh
      - name: Test
        run: cijail ./ci/test.sh
  macos:
    runs-on: macos-latest
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
      # run each test for 5 seconds
      ARBTEST_BUDGET_MS: 5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --workspace --all-targets
  publish-crates:
    needs: [ubuntu, macos]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igankevich/stuckliste-ci:latest
      options: --cap-add SYS_PTRACE
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
      CIJAIL_ENDPOINTS: |
        https://github.com/lyz-code/yamlfix/
        https://pypi.org/simple/
        https://files.pythonhosted.org/packages/
        https://static.crates.io/crates/
        https://index.crates.io/
        https://github.com/rustsec/advisory-db
        https://static.rust-lang.org/dist/
        https://github.com/igankevich/kpea/
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          CIJAIL_ENDPOINTS: |
            ${{ env.CIJAIL_ENDPOINTS }}
            https://crates.io/api/v1/crates/new
        # running with cijail give symbolic link loop error:
        # [Sun Dec 08 14:21:28 2024] cijail: Symbolic link loop (os error 40)
        # rm: error while loading shared libraries: libc.so.6: cannot open shared object file: Error 38
        run: ./ci/publish.sh
  publish-binaries:
    needs: [ubuntu, macos]
    permissions:
      content: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igankevich/stuckliste-ci:latest
      options: --cap-add SYS_PTRACE
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Init
        run: ./ci/init.sh
      - name: Build static binaries
        run: ./ci/build.sh
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload binaries
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stuckliste-${{  github.ref_name }}.tar.gz
          asset_name: stuckliste-${{  github.ref_name }}.tar.gz
          asset_content_type: application/gzip
